### ISSUE TITLE
Due date removed when rescheduling tasks

### ISSUE THREAD

**Issue by MCWopper** [joshuatazrein/obsidian-time-ruler#66] opened 2023-10-08 13:50 UTC
**Describe the bug**
Currenly when dragging a task in the interface to schedule a new time, the due date gets removed. All other elements are kept

**To Reproduce**
1. Create task
2. Add metadate like: tags, due, length, priority
3. Open Time Ruler
4. Drag task to a new time
5. Everything is kept exept due date is removed, schedule time is updated

Same goes for dragging task length

I've tested it with the Dataview, Full Calendar and Tasks Field Format. All the same result

**Expected behavior**
Due date should remain along with other metadata

**Obsidian Version:** 
- [v1.4.14] Desktop

**Plugin Version**
- [1.4.0] Desktop

**Comment by joshuatazrein** [comment] 2023-10-08 19:39
This is fixed in the upcoming release.

**Comment by MCWopper** [comment] 2023-10-09 15:00
I'm impressed with the quick reply and quick fix. 
Minor thing I noticed is that now the due date is kept but the due time isn't.

I don't think I'll use due time but it would make sense if the due time is also kept when updating tasks.

A bigger issue I now have with 1.5.0 is that the task length no longer works.
When dragging lenght obsidian freeses for a few seconds and then nothing happens. Writing the length:: after the tasks does seem to work.

I haven't tested it fully yet but the Time Ruler window crashes and goes blank when removing the "h" from the length:: value. It seems that the length variable doesn't have a invalid check like the schedule time/date or due time/date

I could seperate these issues into new tickets if you prefer.

**Comment by joshuatazrein** [comment] 2023-10-09 15:02
I can take a look at those issues. Right now TR only supports due dates, but not due times. Scheduled can be attached to a time, but deadlines only show up in all-day view and don't get saved. I can at least make it so Time Ruler doesn't rewrite the times.

**Comment by joshuatazrein** [comment] 2023-10-09 15:04
As far as the length issue, I can't reproduce it. Which format are you using?

**Comment by MCWopper** [comment] 2023-10-09 17:40
That could expain why the due time isn't kept. instances where due time are important are very few.

I've done some more testing for length and created a new vault just in case it's a setting issue. From that I found that on my main vault it takes about 5 seconds for the length script/code to run/activate before I can see the color change and can drag a length. I didn't give the plugin enough time to process and released the mouse before I could drag.

In the new test vault it was a lot quicker and works just fine.

Though even in the test fault giving a incorrect length value the Time Ruler window goes blank and I have to close Time Ruler and open it again.

So: 
- Length:: 1h = no issues
- Length:: 1 = blank window

**Comment by joshuatazrein** [comment] 2023-10-09 18:47
I've made some major performance improvements that will come out in a few days, so that issue will be much better.

**Comment by joshuatazrein** [comment] 2023-10-22 04:42
This is fixed in 1.5.1.

**Closed by joshuatazrein** 2023-10-22 04:42 UTC
